name: Create "Merge main into next" PR
on:
  push:
    branches:
      - main
jobs:
  main-into-next:
    name: Create "Merge main into next" PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed to also fetch next branch

      - name: Setup Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Merge main into next
        run: |
          git checkout next
          git merge main
      - name: Add files with conflicts
        if: failure()
        run: |
          git add .
          git commit -m "Merge main into next"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Merge main into next"
          body: |
            This is an automated pull request to merge changes from `main` into `next`.
          base: next
          branch: merge-main-into-next
